package bee.ris.rushhour.consumers;

import java.io.IOException;
import javax.servlet.http.*;

/**
 * This class consumes the data (generated by the <code>IProducer</code>)
 * stored by the <code>StoreManager</code> and delivers it to the RushHour
 * client.
 * @author Rishabh Rao
 */
@SuppressWarnings("serial")
public class Consumer extends HttpServlet {
	public void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws IOException {
		resp.setContentType("text/html");		
	}
}
